apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-app-from-git-source
spec:
  inputs:
    resources:
      - name: source-repo
        type: git
    params:
      - name: pathToContext
        type: string
        description:
        default: /workspace/docker-source
  steps:
    - name: build-and-push
      image: golang:latest
      workingDir: "${inputs.params.pathToContext}"
      command:
        - go
      args:
        - build
        - -v
        - main.go
        - -o
        - /mnt/build/main
      volumeMounts:
        - mountPath: /mnt/build
          name: build-output
  volumes:
    - name: build-output
      emptyDir: {}
