apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    resources:
      - name: source-repo
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/source-repo/Dockerfile
      - name: pathToContext
        type: string
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/docker-source
  outputs:
    resources:
      - name: builtImage
        type: image
  # steps:
  #   - name: build-and-push
  #     image: gcr.io/kaniko-project/executor:v0.9.0
  #     # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
  #     env:
  #       - name: "DOCKER_CONFIG"
  #         value: "/builder/home/.docker/"
  #     workingDir: "${inputs.params.pathToContext}"
  #     command:
  #       - /kaniko/executor
  #     args:
  #       - --dockerfile=${inputs.params.pathToDockerFile}
  #       - --destination=${outputs.resources.builtImage.url}
  #       - --context=${inputs.params.pathToContext}
  #       - --insecure
  steps:
    - name: dockerfile-build
      image: gcr.io/cloud-builders/docker
      workingDir: "${inputs.params.pathToContext}"
      args:
        [
          "build",
          "--no-cache",
          "--tag",
          "${outputs.resources.image}",
          "--file",
          "${inputs.params.pathToDockerFile}",
          ".",
        ]
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
    - name: dockerfile-push
      image: gcr.io/cloud-builders/docker
      args: ["push", "${outputs.resources.image}"]
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock

  # As an implementation detail, this Task mounts the host's daemon socket.
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
