apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-app-from-git-source
spec:
  inputs:
    resources:
      - name: source-repo
        type: git
    params:
      - name: pathToSource
        type: string
        description:
        default: /workspace/source-repo
  steps:
    - name: compile
      image: golang:latest
      workingDir: "${inputs.params.pathToSource}/hello"
      command:
        - go
      args:
        - build
        - -o
        - /mnt/build/hello
        - hello.go
      volumeMounts:
        - mountPath: /mnt/build
          name: build-output
    - name: run
      image: ubuntu:latest
      command:
        - /mnt/build/hello
      volumeMounts:
        - mountPath: /mnt/build
          name: build-output
  volumes:
    - name: build-output
      emptyDir: {}
