apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: web-image
spec:
  type: image
  params:
    #configure: replace with where the image should go: perhaps your local registry or Dockerhub with a secret and configured service account
    - name: url
      value: docker-registry.default.svc.cluster.local/broker-pipelines/demo-image
